### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by danaugrs** [wanadev/collision-gjk-epa#2]
Hi! On Chrome (66.0.3359.181) nothing shows up and I get this error in the developer console:

```
Uncaught ReferenceError: BABYLON is not defined
at demo2d.js:4
```

**Comment by clementlevasseur** [comment]
Hello danaugrs, 

The demo probably does not working, but the tool is ok, we use it on https://www.kozikaza.com/kazaplan/new for the collisions.
I'll fix the demo soon! Thanks for the issue.

**Comment by danaugrs** [comment]
Oh cool, thanks! Kazaplan feels very robust - great work!
